apiVersion: 1

datasources:
  - name: RunabilityInflux
    uid: RunabilityInflux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: runability
      defaultBucket: runability
      tlsSkipVerify: true
    secureJsonData:
      token: runability-super-secret-token
    editable: true
